<?php 
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_5992ccfb49655',
	'title' => 'Header Opties',
	'fields' => array (
		array (
			'key' => 'field_5992cd010d4f0',
			'label' => 'Headlines',
			'name' => 'headlines',
			'type' => 'repeater',
			'instructions' => 'Voer hier de zinnen in voor in de header',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => array (
				array (
					'key' => 'field_599d6fb02d7c4',
					'label' => 'Zinnen',
					'name' => 'lines',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_599d706521798',
							'label' => 'Oranje Tekst',
							'name' => 'line_orange',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_599d705021797',
							'label' => 'Zwarte Tekst',
							'name' => 'line_black',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
				),
			),
		),
		array (
			'key' => 'field_5992cd140d4f2',
			'label' => 'Oranje Knop',
			'name' => 'btn_orange',
			'type' => 'group',
			'instructions' => 'Tekst en URL voor de oranje knop in de header',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_5993fa2c524c3',
					'label' => 'Tekst',
					'name' => 'text',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5993fa3f524c4',
					'label' => 'URL',
					'name' => 'url',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_599c37c442dfe',
					'label' => 'Pijl',
					'name' => 'arrow',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'none' => 'Geen',
						'up' => 'Omhoog',
						'down' => 'Omlaag',
						'right' => 'Rechts',
						'left' => 'links',
					),
					'default_value' => array (
						0 => 'none',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 1,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
			),
		),
		array (
			'key' => 'field_5992cd190d4f3',
			'label' => 'Zwarte Knop',
			'name' => 'btn_black',
			'type' => 'group',
			'instructions' => 'Tekst en URL voor de zwarte knop in de header',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_5993fb421eb23',
					'label' => 'Tekst',
					'name' => 'text',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5993fb4e1eb24',
					'label' => 'URL',
					'name' => 'url',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array (
			'key' => 'field_5992cd1e0d4f4',
			'label' => 'Voorgrondafbeelding',
			'name' => 'header_foreground',
			'type' => 'image',
			'instructions' => 'Afbeelding aan de rechterkant in de header',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => 'png',
		),
		array (
			'key' => 'field_5993e96913420',
			'label' => 'Achtergrondafbeelding',
			'name' => 'header_background',
			'type' => 'image',
			'instructions' => 'De achtergrond afbeelding van de header. Is standaard de studio',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => 'jpg,png',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'cases',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'teamleden',
			),
		),
	),
	'menu_order' => 10,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_59a5830e87d0c',
	'title' => 'Quotes Opties',
	'fields' => array (
		array (
			'key' => 'field_59a5831f91a4f',
			'label' => 'Functie',
			'name' => 'company_position',
			'type' => 'text',
			'instructions' => 'Functie binnen het bedrijf',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Werknemer',
			'placeholder' => 'Accountant, Designer, IT Security Specialist....',
			'prepend' => '',
			'append' => '',
			'maxlength' => 40,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'quotes',
			),
		),
	),
	'menu_order' => 11,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_59a6d3922974a',
	'title' => 'Voorpagina Opties',
	'fields' => array (
		array (
			'key' => 'field_59a6d3a5f87ab',
			'label' => 'Merken',
			'name' => 'brands',
			'type' => 'relationship',
			'instructions' => 'Merken die op de voorpagina getoond worden',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'merken',
			),
			'taxonomy' => array (
			),
			'filters' => array (
				0 => 'search',
			),
			'elements' => '',
			'min' => '',
			'max' => '',
			'return_format' => 'object',
		),
		array (
			'key' => 'field_59a6d3d1f87ac',
			'label' => 'Quotes',
			'name' => 'quotes',
			'type' => 'relationship',
			'instructions' => 'Quotes die op de voorpagina getoond worden',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'quotes',
			),
			'taxonomy' => array (
			),
			'filters' => array (
				0 => 'search',
			),
			'elements' => '',
			'min' => '',
			'max' => '',
			'return_format' => 'object',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_type',
				'operator' => '==',
				'value' => 'front_page',
			),
		),
	),
	'menu_order' => 11,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_59a4132addb54',
	'title' => 'Contact Informatie',
	'fields' => array (
		array (
			'key' => 'field_59a41347d7b2d',
			'label' => 'Titel Links',
			'name' => 'title_left',
			'type' => 'text',
			'instructions' => 'Tekst aan de linkerkant van het contact blok',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_59a4135ad7b2e',
			'label' => 'Titel Rechts',
			'name' => 'title_right',
			'type' => 'text',
			'instructions' => 'Tekst aan de rechterkant van het contact blok',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'teamleden',
			),
		),
	),
	'menu_order' => 15,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_5989981e1f1ed',
	'title' => 'Persoons Informatie',
	'fields' => array (
		array (
			'key' => 'field_59a58635cfbb7',
			'label' => 'Functie',
			'name' => 'company_position',
			'type' => 'text',
			'instructions' => 'Functie binnen het bedrijf',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Werknemer',
			'placeholder' => 'Marketing, Developer, Designer',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_5989982424d80',
			'label' => 'Email',
			'name' => 'email',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'voornaam@indrukwekkend.nl',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_5989983124d81',
			'label' => 'Vaste Telefoon',
			'name' => 'landline',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_5989989924d82',
			'label' => 'Mobiele telefoon',
			'name' => 'mobile',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_5994047115b61',
			'label' => 'Handtekening',
			'name' => 'autograph',
			'type' => 'text',
			'instructions' => 'Voer hier de bestandsnaam in voor de handtekening.
Dit veld kan later nog veranderen en misschien komen te vervallen.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_5996fe16aa36e',
			'label' => 'Social Media',
			'name' => 'social_media',
			'type' => 'repeater',
			'instructions' => 'Voer hier alle Social Media netwerken in die gebruikt worden.
De gebruikersnaam word getoond op de site',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5996fe47aa36f',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Voeg Dienst toe',
			'sub_fields' => array (
				array (
					'key' => 'field_5996fe47aa36f',
					'label' => 'Dienst',
					'name' => 'service',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'facebook' => 'Facebook',
						'instagram' => 'Instagram',
						'linkedin' => 'Linkedin',
						'twitter' => 'Twitter',
						'strava' => 'Strava',
						'vsco' => 'VSCO',
						'vsco-2' => 'VSCO 2',
						'website' => 'Website',
					),
					'default_value' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array (
					'key' => 'field_5996fe53aa370',
					'label' => 'Gebruikersnaam',
					'name' => 'username',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5996fe60aa371',
					'label' => 'URL',
					'name' => 'url',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'teamleden',
			),
		),
	),
	'menu_order' => 16,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_599c29dc09245',
	'title' => 'Pagina Inhoud',
	'fields' => array (
		array (
			'key' => 'field_599c2ad6a3cbb',
			'label' => 'Primair Inhoud',
			'name' => 'primary_content',
			'type' => 'flexible_content',
			'instructions' => 'Inhoud voor het grijze deel van de pagina',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layouts' => array (
				'599ed308fcc36' => array (
					'key' => '599ed308fcc36',
					'name' => 'content_left',
					'label' => 'Tekst Links',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_599ed308fcc37',
							'label' => 'Titel',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_599ed308fcc38',
							'label' => 'Inhoud',
							'name' => 'content',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '70',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => 'wpautop',
						),
					),
					'min' => '',
					'max' => '',
				),
				'599ed31afcc3b' => array (
					'key' => '599ed31afcc3b',
					'name' => 'content_right',
					'label' => 'Tekst Rechts',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_599ed31afcc3d',
							'label' => 'Inhoud',
							'name' => 'content',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '70',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => 'wpautop',
						),
						array (
							'key' => 'field_599ed31afcc3c',
							'label' => 'Titel',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'598861bb7b9de' => array (
					'key' => '598861bb7b9de',
					'name' => 'heading_left',
					'label' => 'Afbeelding Links',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_599c2ad6a3cbc',
							'label' => 'Titel',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_599c2ad6a3cbd',
							'label' => 'Inhoud',
							'name' => 'content',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '70',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => 'wpautop',
						),
						array (
							'key' => 'field_599c2ad6a3cbe',
							'label' => 'Afbeelding',
							'name' => 'image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array (
							'key' => 'field_599c2ad6a3cbf',
							'label' => 'Afbeelding onderschrift',
							'name' => 'image_description',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '70',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'5988727150a63' => array (
					'key' => '5988727150a63',
					'name' => 'heading_right',
					'label' => 'Afbeelding Rechts',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_599c2ad6a3cc1',
							'label' => 'Inhoud',
							'name' => 'content',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '70',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => 'wpautop',
						),
						array (
							'key' => 'field_599c2ad6a3cc0',
							'label' => 'Titel',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_599c2ad6a3cc3',
							'label' => 'Afbeelding onderschrift',
							'name' => 'image_description',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '70',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_599c2ad6a3cc2',
							'label' => 'Afbeelding',
							'name' => 'image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'59897888626d8' => array (
					'key' => '59897888626d8',
					'name' => 'heading_full_left',
					'label' => 'Afbeelding Volledig Links',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_599c2ad6a3cc4',
							'label' => 'Titel',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_599c2ad6a3cc5',
							'label' => 'Inhoud',
							'name' => 'content',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '70',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => 'wpautop',
						),
						array (
							'key' => 'field_599c2ad6a3cc6',
							'label' => 'Afbeelding',
							'name' => 'image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '60',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array (
							'key' => 'field_599c2ad6a3cc7',
							'label' => 'Volledige breedte',
							'name' => 'fullwidth',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '20',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 1,
							'ui' => 1,
							'ui_on_text' => 'Aan',
							'ui_off_text' => 'Uit',
						),
						array (
							'key' => 'field_599c2ad6a3cc8',
							'label' => 'Uitlijning',
							'name' => 'alignment',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_599c2ad6a3cc7',
										'operator' => '!=',
										'value' => '1',
									),
								),
							),
							'wrapper' => array (
								'width' => '20',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'left' => 'Links',
								'right' => 'Rechts',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => '',
							'layout' => 'horizontal',
							'return_format' => 'value',
						),
						array (
							'key' => 'field_59a4207e2a6b9',
							'label' => 'Afbeelding onderschrift',
							'name' => 'image_description',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '70',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'599d6391b1ecf' => array (
					'key' => '599d6391b1ecf',
					'name' => 'heading_full_right',
					'label' => 'Afbeelding Volledig Rechts',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_599d6391b1ed2',
							'label' => 'Inhoud',
							'name' => 'content',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '70',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => 'wpautop',
						),
						array (
							'key' => 'field_599d6391b1ed0',
							'label' => 'Titel',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_599d6391b1ed3',
							'label' => 'Afbeelding',
							'name' => 'image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '60',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array (
							'key' => 'field_599d6391b1ed4',
							'label' => 'Volledige breedte',
							'name' => 'fullwidth',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '20',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 1,
							'ui' => 1,
							'ui_on_text' => 'Aan',
							'ui_off_text' => 'Uit',
						),
						array (
							'key' => 'field_599d6391b1ed5',
							'label' => 'Uitlijning',
							'name' => 'alignment',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_599d6391b1ed4',
										'operator' => '!=',
										'value' => '1',
									),
								),
							),
							'wrapper' => array (
								'width' => '20',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'left' => 'Links',
								'right' => 'Rechts',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => '',
							'layout' => 'horizontal',
							'return_format' => 'value',
						),
						array (
							'key' => 'field_59a4208e2a6ba',
							'label' => 'Afbeelding onderschrift',
							'name' => 'image_description',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '70',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'5996a6bb29afe' => array (
					'key' => '5996a6bb29afe',
					'name' => 'heading_gallery_left',
					'label' => 'Gallerij Links',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_599c2ad6a3cc9',
							'label' => 'Titel',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_599c2ad6a3cca',
							'label' => 'Inhoud',
							'name' => 'content',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '70',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => 'wpautop',
						),
						array (
							'key' => 'field_599c2ad6a3ccb',
							'label' => 'Afbeeldingen',
							'name' => 'images',
							'type' => 'repeater',
							'instructions' => 'Kies 1 tot 4 afbeeldingen.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => 'field_599c2ad6a3ccc',
							'min' => 1,
							'max' => 4,
							'layout' => 'block',
							'button_label' => 'Afbeelding Toevoegen',
							'sub_fields' => array (
								array (
									'key' => 'field_599c2ad6a3ccc',
									'label' => 'Afbeelding',
									'name' => 'image',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'url',
									'preview_size' => 'thumbnail',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'599d67d93288b' => array (
					'key' => '599d67d93288b',
					'name' => 'heading_gallery_right',
					'label' => 'Gallerij Rechts',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_599d67d93288d',
							'label' => 'Inhoud',
							'name' => 'content',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '70',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => 'wpautop',
						),
						array (
							'key' => 'field_599d67d93288c',
							'label' => 'Titel',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_599d67d93288e',
							'label' => 'Afbeeldingen',
							'name' => 'images',
							'type' => 'repeater',
							'instructions' => 'Kies 1 tot 4 afbeeldingen.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => 'field_599d67d93288f',
							'min' => 1,
							'max' => 4,
							'layout' => 'block',
							'button_label' => 'Afbeelding Toevoegen',
							'sub_fields' => array (
								array (
									'key' => 'field_599d67d93288f',
									'label' => 'Afbeelding',
									'name' => 'image',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'url',
									'preview_size' => 'thumbnail',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'59a40ab4642c6' => array (
					'key' => '59a40ab4642c6',
					'name' => 'quote_left',
					'label' => 'Quote Links',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_59a40ac1642c7',
							'label' => 'Quote',
							'name' => 'content',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => 'wpautop',
						),
						array (
							'key' => 'field_59a40ada642c8',
							'label' => 'Auteur',
							'name' => 'author',
							'type' => 'post_object',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array (
								0 => 'teamleden',
							),
							'taxonomy' => array (
							),
							'allow_null' => 0,
							'multiple' => 0,
							'return_format' => '',
							'ui' => 1,
						),
					),
					'min' => '',
					'max' => '',
				),
				'59a40b35642c9' => array (
					'key' => '59a40b35642c9',
					'name' => 'quote_right',
					'label' => 'Quote Rechts',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_59a40b35642ca',
							'label' => 'Quote',
							'name' => 'content',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => 'wpautop',
						),
						array (
							'key' => 'field_59a40b35642cb',
							'label' => 'Auteur',
							'name' => 'author',
							'type' => 'post_object',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array (
								0 => 'teamleden',
							),
							'taxonomy' => array (
							),
							'allow_null' => 0,
							'multiple' => 0,
							'return_format' => 'id',
							'ui' => 1,
						),
					),
					'min' => '',
					'max' => '',
				),
				'599ad547df5e0' => array (
					'key' => '599ad547df5e0',
					'name' => 'socialmedia',
					'label' => 'Social Media',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_599c2ad6a3ccd',
							'label' => 'Titel',
							'name' => 'socialmedia_title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '20',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_599c2ad6a3cce',
							'label' => 'Social Media',
							'name' => '',
							'type' => 'message',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '20',
								'class' => '',
								'id' => '',
							),
							'message' => 'Hier komen de Social Media items van het Teamlid.',
							'new_lines' => 'wpautop',
							'esc_html' => 0,
						),
						array (
							'key' => 'field_599c2ad6a3cd2',
							'label' => 'Knop Tekst',
							'name' => 'socialmedia_btn_text',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '20',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_599c2ad6a3cd3',
							'label' => 'Knop URL',
							'name' => 'socialmedia_btn_url',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '20',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_59ad1f21c25b0',
							'label' => 'Pijl',
							'name' => 'arrow',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '20',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'none' => 'Geen',
								'up' => 'Omhoog',
								'down' => 'Omlaag',
								'right' => 'Rechts',
								'left' => 'links',
							),
							'default_value' => array (
								0 => 'none',
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
			),
			'button_label' => 'Rij toevoegen',
			'min' => '',
			'max' => '',
		),
		array (
			'key' => 'field_599ed35121c53',
			'label' => 'Secundair Inhoud',
			'name' => 'secondary_content',
			'type' => 'flexible_content',
			'instructions' => 'Inhoud voor het witte deel van de pagina',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layouts' => array (
				'599ed308fcc36' => array (
					'key' => '599ed308fcc36',
					'name' => 'content_left',
					'label' => 'Tekst Links',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_599ed35121c54',
							'label' => 'Titel',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_599ed35121c55',
							'label' => 'Inhoud',
							'name' => 'content',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '70',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => 'wpautop',
						),
					),
					'min' => '',
					'max' => '',
				),
				'599ed31afcc3b' => array (
					'key' => '599ed31afcc3b',
					'name' => 'content_right',
					'label' => 'Tekst Rechts',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_599ed35121c57',
							'label' => 'Inhoud',
							'name' => 'content',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '70',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => 'wpautop',
						),
						array (
							'key' => 'field_599ed35121c56',
							'label' => 'Titel',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'598861bb7b9de' => array (
					'key' => '598861bb7b9de',
					'name' => 'heading_left',
					'label' => 'Afbeelding Links',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_599ed35121c58',
							'label' => 'Titel',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_599ed35121c59',
							'label' => 'Inhoud',
							'name' => 'content',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '70',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => 'wpautop',
						),
						array (
							'key' => 'field_599ed35121c5a',
							'label' => 'Afbeelding',
							'name' => 'image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array (
							'key' => 'field_599ed35121c5b',
							'label' => 'Afbeelding onderschrift',
							'name' => 'image_description',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '70',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'5988727150a63' => array (
					'key' => '5988727150a63',
					'name' => 'heading_right',
					'label' => 'Afbeelding Rechts',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_599ed35121c5c',
							'label' => 'Inhoud',
							'name' => 'content',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '70',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => 'wpautop',
						),
						array (
							'key' => 'field_599ed35121c5d',
							'label' => 'Titel',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_599ed35121c5e',
							'label' => 'Afbeelding onderschrift',
							'name' => 'image_description',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '70',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_599ed35121c5f',
							'label' => 'Afbeelding',
							'name' => 'image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'59897888626d8' => array (
					'key' => '59897888626d8',
					'name' => 'heading_full_left',
					'label' => 'Afbeelding Volledig Links',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_599ed35121c60',
							'label' => 'Titel',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_599ed35121c61',
							'label' => 'Inhoud',
							'name' => 'content',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '70',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => 'wpautop',
						),
						array (
							'key' => 'field_599ed35121c62',
							'label' => 'Afbeelding',
							'name' => 'image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '60',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array (
							'key' => 'field_599ed35121c63',
							'label' => 'Volledige breedte',
							'name' => 'fullwidth',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '20',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 1,
							'ui' => 1,
							'ui_on_text' => 'Aan',
							'ui_off_text' => 'Uit',
						),
						array (
							'key' => 'field_599ed35121c64',
							'label' => 'Uitlijning',
							'name' => 'alignment',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_599ed35121c63',
										'operator' => '!=',
										'value' => '1',
									),
								),
							),
							'wrapper' => array (
								'width' => '20',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'left' => 'Links',
								'right' => 'Rechts',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => '',
							'layout' => 'horizontal',
							'return_format' => 'value',
						),
					),
					'min' => '',
					'max' => '',
				),
				'599d6391b1ecf' => array (
					'key' => '599d6391b1ecf',
					'name' => 'heading_full_right',
					'label' => 'Afbeelding Volledig Rechts',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_599ed35121c65',
							'label' => 'Inhoud',
							'name' => 'content',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '70',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => 'wpautop',
						),
						array (
							'key' => 'field_599ed35121c66',
							'label' => 'Titel',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_599ed35121c67',
							'label' => 'Afbeelding',
							'name' => 'image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '60',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array (
							'key' => 'field_599ed35121c68',
							'label' => 'Volledige breedte',
							'name' => 'fullwidth',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '20',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 1,
							'ui' => 1,
							'ui_on_text' => 'Aan',
							'ui_off_text' => 'Uit',
						),
						array (
							'key' => 'field_599ed35121c69',
							'label' => 'Uitlijning',
							'name' => 'alignment',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_599ed35121c68',
										'operator' => '!=',
										'value' => '1',
									),
								),
							),
							'wrapper' => array (
								'width' => '20',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'left' => 'Links',
								'right' => 'Rechts',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => '',
							'layout' => 'horizontal',
							'return_format' => 'value',
						),
					),
					'min' => '',
					'max' => '',
				),
				'5996a6bb29afe' => array (
					'key' => '5996a6bb29afe',
					'name' => 'heading_gallery_left',
					'label' => 'Gallerij Links',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_599ed35121c6a',
							'label' => 'Titel',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_599ed35121c6b',
							'label' => 'Inhoud',
							'name' => 'content',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '70',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => 'wpautop',
						),
						array (
							'key' => 'field_599ed35121c6c',
							'label' => 'Afbeeldingen',
							'name' => 'images',
							'type' => 'repeater',
							'instructions' => 'Kies 1 tot 4 afbeeldingen.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => 'field_599c2ad6a3ccc',
							'min' => 1,
							'max' => 4,
							'layout' => 'block',
							'button_label' => 'Afbeelding Toevoegen',
							'sub_fields' => array (
								array (
									'key' => 'field_599ed35121c6d',
									'label' => 'Afbeelding',
									'name' => 'image',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'url',
									'preview_size' => 'thumbnail',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'599d67d93288b' => array (
					'key' => '599d67d93288b',
					'name' => 'heading_gallery_right',
					'label' => 'Gallerij Rechts',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_599ed35121c6e',
							'label' => 'Inhoud',
							'name' => 'content',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '70',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => 'wpautop',
						),
						array (
							'key' => 'field_599ed35121c6f',
							'label' => 'Titel',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_599ed35121c70',
							'label' => 'Afbeeldingen',
							'name' => 'images',
							'type' => 'repeater',
							'instructions' => 'Kies 1 tot 4 afbeeldingen.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => 'field_599d67d93288f',
							'min' => 1,
							'max' => 4,
							'layout' => 'block',
							'button_label' => 'Afbeelding Toevoegen',
							'sub_fields' => array (
								array (
									'key' => 'field_599ed35121c71',
									'label' => 'Afbeelding',
									'name' => 'image',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'url',
									'preview_size' => 'thumbnail',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
			),
			'button_label' => 'Rij toevoegen',
			'min' => '',
			'max' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
			array (
				'param' => 'page_type',
				'operator' => '!=',
				'value' => 'front_page',
			),
			array (
				'param' => 'page_template',
				'operator' => '!=',
				'value' => 'template-contact.php',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'teamleden',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'cases',
			),
		),
	),
	'menu_order' => 20,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_598861b10b0c6',
	'title' => 'Cases',
	'fields' => array (
		array (
			'key' => 'field_59a552812f78e',
			'label' => 'Cases Titel',
			'name' => 'cases_title',
			'type' => 'text',
			'instructions' => 'Tekst als begeleidende titel',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Iets van; Bekijk meer cases',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_599aaa80a1c1d',
			'label' => 'Cases',
			'name' => 'cases',
			'type' => 'relationship',
			'instructions' => 'Kies de Cases die je wilt tonen op de pagina',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'cases',
			),
			'taxonomy' => array (
			),
			'filters' => array (
				0 => 'search',
			),
			'elements' => '',
			'min' => '',
			'max' => 4,
			'return_format' => 'object',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'cases',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'teamleden',
			),
		),
	),
	'menu_order' => 30,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_59a58239cdca9',
	'title' => 'Client Quote',
	'fields' => array (
		array (
			'key' => 'field_59a58242190b0',
			'label' => 'Client Quote',
			'name' => 'quote_client',
			'type' => 'post_object',
			'instructions' => 'Kies een Quote van de klant',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'quotes',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'cases',
			),
		),
	),
	'menu_order' => 40,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_59a582d2f1b41',
	'title' => 'Manager Quote',
	'fields' => array (
		array (
			'key' => 'field_59a582d752415',
			'label' => 'Manager Quote',
			'name' => 'quote_manager',
			'type' => 'textarea',
			'instructions' => 'Voer hier een korte quote in van de projectmanager',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => 60,
			'rows' => '',
			'new_lines' => '',
		),
		array (
			'key' => 'field_59a584f37536c',
			'label' => 'Manager',
			'name' => 'manager',
			'type' => 'post_object',
			'instructions' => 'Kies de manager van dit project',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '80',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'teamleden',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
		),
		array (
			'key' => 'field_59a68bce96864',
			'label' => 'Tekst Grootte',
			'name' => 'heading_size',
			'type' => 'select',
			'instructions' => 'Kies een lettergrootte. H1 is het grootst, H6 is het kleinst',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'h1' => 'Heading 1',
				'h2' => 'Heading 2',
				'h3' => 'Heading 3',
				'h4' => 'Heading 4',
				'h5' => 'Heading 5',
				'h6' => 'Heading 6',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'cases',
			),
		),
	),
	'menu_order' => 50,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;
?>